export async function downloadPdf(
  elementId: string,
  clientName: string,
  contentType: string
): Promise<void> {
  const html2canvas = (await import('html2canvas')).default;
  const { jsPDF } = await import('jspdf');

  const element = document.getElementById(elementId);
  if (!element) return;

  const canvas = await html2canvas(element, { scale: 2, useCORS: true });
  const imgData = canvas.toDataURL('image/png');

  const imgWidth = 210; // A4 width in mm
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  const pdf = new jsPDF('p', 'mm', 'a4');
  pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);

  // Watermark
  pdf.setFontSize(8);
  pdf.setTextColor(150, 150, 150);
  pdf.text('Generated by ClubSheIs Content Studio', 105, imgHeight + 5, {
    align: 'center',
  });

  const date = new Date().toISOString().split('T')[0];
  pdf.save(`${clientName}_${contentType}_${date}.pdf`);
}

export function downloadTxt(
  content: string,
  clientName: string,
  contentType: string
): void {
  const date = new Date().toISOString().split('T')[0];
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${clientName}_${contentType}_${date}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function copyToClipboard(content: string): Promise<void> {
  return navigator.clipboard.writeText(content);
}

export function stripJsonFormatting(content: string): string {
  try {
    const parsed = JSON.parse(content);
    if (Array.isArray(parsed)) {
      return parsed
        .map((item, i) => {
          const parts = [];
          if (item.slide) parts.push(`SLIDE ${item.slide}`);
          if (item.headline) parts.push(`Headline: ${item.headline}`);
          if (item.body) parts.push(item.body);
          if (item.designNote) parts.push(`[Design note: ${item.designNote}]`);
          return parts.join('\n');
        })
        .join('\n\n---\n\n');
    }
    return content;
  } catch {
    return content;
  }
}
